version: 2
updates:
  # Python dependencies
  - package-ecosystem: pip
    directory: "/"
    schedule:
      # Corrected spelling from "dialy" to "daily"
      interval: daily
    # Limiting open PRs to prevent noise
    open-pull-requests-limit: 3

  # Node.js dependencies (React frontend)
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: daily
    # Limiting open PRs helps keep pull requests more manageable
    open-pull-requests-limit: 3

  # Docker dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3

  # GitHub Actions dependencies in .github directory
  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"

  # Git submodules (if using any)
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
