version: 2
updates:
  # Python dependencies (backend)
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "chore"
      include: scope

  # Node.js dependencies (React frontend)
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - javascript
      - frontend
    commit-message:
      prefix: "chore"
      include: scope

  # Docker dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - docker

  # GitHub Actions workflows
  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "chore"
      include: scope

  # Git submodules (if in use)
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - submodule
