from .auth import auth_bp
from .quests import quests_bp
from .marketplace import marketplace_bp
from .economy import economy_bp
from .users import users_bp
from .transactions import transactions_bp
from .user_quests import user_quests_bp
from .admin import admin_bp
from .analytics import analytics_bp
from .health import health_bp
